### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by AlexJHomer** [ids-s1-21/website#2]
- Week 1, Assignments: "This weeks assignment" -> "This week's assignment"
- Final Projects, Tips: "you're welcomed" -> "you're welcome"
- Final Projects, Peer Evaluation: "pleaseprovide" -> "please provide"
- Quizes, title: should be "Quizzes"
- Workshops: "can't make any of the workshops times" -> "can't make any of the workshops' times" (or "times of the workshops", which maybe sounds more natural?
- Workshops: "each others'" -> "each other's"
- Help, tip section: stray square brackets, I think?
- Policies: stray square bracket right at the end

**Comment by Eldave93** [comment]
All typos addressed (thanks). I typically use square brackets where I need to confirm if some information is correct so its a placeholder.
