### ISSUE TITLE
Various points on the "Final projects" page

### ISSUE THREAD

**Issue by AlexJHomer** [ids-s1-21/website#4]
(As well as a couple of typos mentioned in #2)

- Maybe change the first sentence to "You, as part of your team, will be responsible for..." This is probably just me not paying enough attention, but I was reading the rest as if it were an individual thing.
- I think (reading down) the last sentence of the first paragraph doesn't apply to any team that pre-records their presentation?
- "There is no limit on what tools or packages you may use, but sticking to packages we learned in class (`tidyverse`) is required." - I'm not sure what this sentence means... Does it mean you have to use the tidyverse, but can use anything else? Or you can only use things we've covered but you don't have to use all of them?
- When I did a project like this as an undergrad we were told to use [the OECD's data](https://data.oecd.org/) - might be worth adding?

**Comment by Eldave93** [comment]
- Good spot, I think this comes from changes from previous years not being noticed.
- Yup, again probably a hold over from the 2019 text.
- I've changed "required" to "advised", I think it was required last year to use the tidyverse for data munging and modeling. We can re-word this to make this more clear if we decide to "require" it but I'm happy to just say it is advised to do this.
- I've added this dataset to the suggestions :)
