### ISSUE TITLE
Suggested reading for Week 2

### ISSUE THREAD

**Issue by AlexJHomer** [ids-s1-21/website#7]
Possibly worth adding [The Layered Grammar of Graphics](http://vita.had.co.nz/papers/layered-grammar.pdf) by Wickham to the optional reading?  The videos mention Wilkinson's *The Grammar of Graphics* (available through DiscoverEd for free, if you've not spotted it), which is conventionally taken as the origin point for `ggplot2`, but as Wickham notes, he "proposes an alternative parameterization of the grammar, based around the idea of building up a graphic from multiple layers of data. The grammar differs from Wilkinson’s in its arrangement of the components, the development of a hierarchy of defaults, and in that it is embedded inside another programming language."  (And I could swear I've seen someone argue that ggplot2 shouldn't claim inspiration from Wilkinson because of that, but I can't find it now...)

(This might still be in the wrong repo, feel free to move if so.)

**Comment by Eldave93** [comment]
Interesting, I'll make sure to add this to the reading list... the additional information I don't know if you want to mention this somewhere in the content available to students?

**Comment by AlexJHomer** [comment]
Yeah, if you leave this open/make a new issue I'll see if I can find a good place to put it.

**Comment by Eldave93** [comment]
Clarified this in the Errata
